# Generated by Django 3.2.25 on 2024-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(default='http://127.0.0.1:8000/static/images/default.jpg'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='http://127.0.0.1:8000/static/images/default.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
